### PR TITLE
Add it and report coverage

### PR DESCRIPTION
**Pull request by jtx1999**
Add integration tests.
Add Github action to report coverage on PRs.

### CODE REVIEW

**Comment by owolabileg** [comment]
> Check the exact tests affected

Has this been fixed @jtx1999 ?

**Comment by owolabileg** [comment]
> Check the exact tests affected

What about this one, @jtx1999 ??

**Comment by jtx1999** [comment]
> > Check the exact tests affected
> 
> What about this one, @jtx1999 ??

@owolabileg Not yet, I'm going to add that

**Comment by owolabileg** [comment]
@jtx1999 what is the status of this PR? Is there a plan to fix the failing build?

**Comment by jtx1999** [comment]
> @jtx1999 what is the status of this PR? Is there a plan to fix the failing build?

@owolabileg
The checks for the exact tests are added.
The Github action for adding comments doesn't work on non-collaborators due to permission [issues](https://github.com/actions/github-script/issues/42).
The failed maven builds were possibly due to Github [outage](https://www.githubstatus.com/incidents/ltvyl42v20j5), will retry soon.

**Comment by jtx1999** [comment]
@owolabileg Please review

**Comment by owolabileg** [comment]
> The Github action for adding comments doesn't work on non-collaborators due to permission

@jtx1999 so, what does the current PR do for coverage instead? Can we add a coverage badge to the dashboard?

**Comment by jtx1999** [comment]
> @jtx1999 so, what does the current PR do for coverage instead? Can we add a coverage badge to the README?

@owolabileg The current PR logs the coverage to stdout in the actions run, e.g. https://github.com/TestingResearchIllinois/starts/pull/72/checks?check_run_id=2687294098
Screen Shot 2021-05-27 at 2 48 45 PM

Can we merge this PR first? I'll add a coverage badge later.

**Comment by owolabileg** [comment]
@jtx1999 see #81

**Pull request merged**
